# PBS configuration

# If submitting to a different project to your default, uncomment line below 
# and change project code as appropriate; also set shortpath below
# project: x77

# Force payu to always find, and save, files in this scratch project directory
# (you may need to add the corresponding PBS -l storage flag in sync_data.sh)
# shortpath: /scratch/v45

queue: normal
ncpus: 240
jobfs: 10GB
mem: 960GB

walltime: 00:30:00
jobname: 025deg_jra55do_ryf

model: access-om3

exe:  /g/data/ik11/spack/0.20.1/opt/linux-rocky8-cascadelake/intel-2021.6.0/access-om3-main-lxbeca7/bin/access-om3-MOM6-CICE6
input: 
    - /g/data/ik11/inputs/access-om3/0.x.0/025deg/share/access-om2-025deg-ESMFmesh.nc # shared grids and topography
    - /g/data/ik11/inputs/access-om3/0.x.0/025deg/share/access-om2-nomask-025deg-ESMFmesh.nc
    - /g/data/ik11/inputs/access-om3/0.x.0/025deg/share/ocean_hgrid.nc
    - /g/data/ik11/inputs/access-om3/0.x.0/025deg/share/ocean_mask.nc
    - /g/data/ik11/inputs/access-om3/0.x.0/025deg/share/topog.nc
    - /g/data/ik11/inputs/access-om3/0.x.0/025deg/mom # grids, ICs etc
    - /g/data/tm70/as2285/om3-scripts/grid_generation/025deg/grid.nc
    - /g/data/tm70/as2285/om3-scripts/grid_generation/025deg/kmt.nc
    - /g/data/ik11/inputs/access-om3/0.x.0/share/meshes/JRA55do-ESMFmesh.nc # mesh for JRA55-do stream
    - /g/data/ik11/inputs/JRA-55/RYF/v1-4/ # datm and drof JRA55-do streams data
 
collate: false
runlog: false

userscripts:
    setup: ./setup_cice_restarts.sh
    archive: ./archive_cice_restarts.sh

modules:
  use:
      - /g/data/ik11/spack/0.20.1/modules/access-om3/0.x.0/linux-rocky8-cascadelake
  load:
      - intel-compiler/2021.6.0
      - openmpi/4.1.4
      - parallelio/2.5.10
