format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6:
  fullpath: /g/data/tm70/as2285/spack0.22/release/linux-rocky8-x86_64/intel-2021.10.0/access-om3-nuopc-git.0.3.1_0.3.1-ubwyic2xxgjatiresdvxtdnrn4jpqem6/bin/access-om3-MOM6-CICE6
  hashes:
    binhash: 08f316ea6726d56bb81204fd97dff039
    md5: 85406a2e40e93eb717b412c20926ae2a
