format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6-Debug-4c25570-modified:
  fullpath: /g/data/tm70/as2285/access-om3/bin/access-om3-MOM6-CICE6-Debug-4c25570-modified
  hashes:
    binhash: 5ede9065684fbd91b7d4e4495f63ac9f
    md5: 837a81676a8d680217b1f1b50ff5f69a
